### ISSUE TITLE
Plugin set up but no emails

### ISSUE THREAD

**Issue by cmlowe** [thebeard/events-calendar-pro-organizer-mail#1]
Hi,

I'm using your plugin with Events Calendar Pro and Wootickets and have saved the settings as you outlined in the readme; however, no emails are being sent to the organizer after the completed purchase.

Do you have any advice for trouble shooting?

Not sure if this matters, but I've changed the display name/label of organizers to 'instructors' via tribe filters.

Thanks,
Chris

![screen shot 2016-05-18 at 3 07 12 pm](https://cloud.githubusercontent.com/assets/148940/15369718/3a1c5252-1d0a-11e6-8c87-73db76066cec.png)

**Comment by cardinalacres** [comment]
Same issue here.

**Comment by thebeard** [comment]
Apologies guys, my notifications were muted. Will look into this.

**Comment by masteradhoc** [comment]
@thebeard any update on this?

**Comment by thebeard** [comment]
hi @masteradhoc and the rest. I was involved with quite a few projects that used the event calendar plugin. At some point a Modern Tribe representative contacted me about getting involved, but was later informed that timezones would conflict. I've since not had any further projects that use event calendars. 

After my last message I had a look at the newer versions of Events Calendar, but couldn't allocate enough time to get my plugin up to date with their recent code changes.

Would love to come back to this and supply a fix, but currently there just doesn't seem to be time. Apologies for the inconvenience.
